"""fixed

Revision ID: 491e41605e9d
Revises: bb9bc0a3943e
Create Date: 2024-10-30 18:16:27.330383

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "491e41605e9d"
down_revision: Union[str, None] = "bb9bc0a3943e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "listings", sa.Column("date_added", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "listings", sa.Column("seller_username", sa.String(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("listings", "seller_username")
    op.drop_column("listings", "date_added")
    # ### end Alembic commands ###
