"""create data

Revision ID: 3d0b8e19de0a
Revises: 
Create Date: 2025-01-21 15:46:20.770335

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3d0b8e19de0a"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "listings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("answer", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_listings_answer"), "listings", ["answer"], unique=False
    )
    op.create_index(op.f("ix_listings_id"), "listings", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_listings_id"), table_name="listings")
    op.drop_index(op.f("ix_listings_answer"), table_name="listings")
    op.drop_table("listings")
    # ### end Alembic commands ###
